### ISSUE TITLE
Action Group Name Length too long (over 12 chars)

### ISSUE THREAD

**Issue by JCoreMS** [Azure/AzureMonitorStarterPacks#109]
I manually specified an action group name within the Custom UI deployment and received the following:
"code": "GroupShortNameIsTooLong",
  "message": "The action group short name 'ag-monstar-email' is too long. Please specify a short name with '12' or less characters."

Suggest adding a regex query to the text box field with something like:
^[a-zA-Z0-9][\\w-]{0,10}[a-zA-Z0-9]$

This regex query ensures that the string has 12 or less characters that can be alphanumeric and include underscores and hyphens, and does not start or end with anything other than an alphanumeric character.

**Comment by josefehse** [comment]
Implemented

**Comment by michel-kamp-work** [comment]
is this already released ? testing the published version and still have this issue
