### ISSUE TITLE
Deployment error 

### ISSUE THREAD

**Issue by ms-amitabh90** [Azure/AzureMonitorStarterPacks#82]
Importing ./Packs/IaaS/Nginx/Azure Monitor Starter Pack _ NGINX-1692341707202.json dashboard.
Command group 'grafana' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
{
  "dashboardId": 14,
  "description": "",
  "folderId": 0,
  "folderUid": "",
  "imported": true,
  "importedUri": "db/azure-monitor-starter-pack-nginx",
  "importedUrl": "/d/AzMonStarPackNGINX/azure-monitor-starter-pack-nginx",
  "path": "",
  "pluginId": "",
  "slug": "azure-monitor-starter-pack-nginx",
  "title": "Azure Monitor Starter Pack / NGINX",
  "uid": "AzMonStarPackNGINX"
}
Deploying pack AMSP-Windows-IIS in CH1-AzureMonitorStarterPacksRG resource group and assigning policies at subscription level.
deploy-pack: 12:36:29 PM - The deployment 'deployment253323123321' failed with error(s). Showing 2 out of 2 error(s). Status Message: Data collection rule is
invalid (Code: InvalidPayload)  - Table for output stream 'Custom-CustomAzMAIISLogs_CL' is not available for destination
'CH1-AzureMonitorStarterPacksLA'. (Code:InvalidOutputTable)   Status Message: At least one resource deployment operation failed. Please list
deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details. (Code: DeploymentFailed)  - Data
collection rule is invalid (Code: InvalidPayload)    - Table for output stream 'Custom-CustomAzMAIISLogs_CL' is not available for destination
'CH1-AzureMonitorStarterPacksLA'. (Code:InvalidOutputTable)    CorrelationId: 3bf6564e-e9dd-47ca-a6fd-37c2ccafea0e
Installing Grafana dashboard for AMSP-Windows-IIS
Importing ./Packs/IaaS/IIS/Azure Monitor Starter Pack _ IIS-1692341727216.json dashboard.
Command group 'grafana' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
{
  "dashboardId": 15,
  "description": "",
  "folderId": 0,
  "folderUid": "",
  "imported": true,
  "importedUri": "db/azure-monitor-starter-pack-iis",
  "importedUrl": "/d/AzMonStarPackIIS/azure-monitor-starter-pack-iis",
  "path": "",
  "pluginId": "",
  "removed": false,
  "slug": "azure-monitor-starter-pack-iis",
  "title": "Azure Monitor Starter Pack / IIS",
  "uid": "AzMonStarPackIIS"
}

**Comment by josefehse** [comment]
Deployement now uses custom portal UI.
